sudo: false
language: python
python:
- '3.6'
- '3.7'
- '3.8'
addons:
  apt:
    packages: libhdf5-serial-dev
install:
- pip install -r requirements.txt
- pip install pytest
- pip install -e .
script:
- pytest -v
notifications:
  slack:
    secure: hBQQXHcN9bGng5GMTwTLA3SYf5yFj4uDP3utnpFcULuCYdKMwxMVIyjUcfkd1bojS9vt2MA8bcWC0vZ9v6EChCGvlGwfSMskOMTv++Gbou4xPrHwbHPDBA9lbnJ5VMN4zazTS4zg6tHIpez1se9YYjo/LwSp6KwV6E5ybeZBkJM=
